def create_theme_presets():
    """
    Return the available app themes.
    """
    return {
        "Classic Gray": {
            "bg": "#c0c0c0",
            "panel": "#d4d0c8",
            "panel_alt": "#ece9d8",
            "panel_soft": "#f3f0e4",
            "border": "#7f7f7f",
            "text": "#111111",
            "muted": "#4e4e4e",
            "canvas": "#808080",
            "field": "#ffffff",
            "field_border": "#7f9db9",
            "accent": "#0a246a",
            "accent_soft": "#b6c7e5",
            "button": "#d4d0c8",
            "button_alt": "#e6e2d8",
            "shadow_dark": "#808080",
            "shadow_light": "#ffffff",
        },
        "XP Blue": {
            "bg": "#dbe7f7",
            "panel": "#ece9d8",
            "panel_alt": "#ffffff",
            "panel_soft": "#f7f4ea",
            "border": "#7f9db9",
            "text": "#0f1728",
            "muted": "#4f6280",
            "canvas": "#6f8db9",
            "field": "#ffffff",
            "field_border": "#7f9db9",
            "accent": "#1f5fbf",
            "accent_soft": "#c8daf5",
            "button": "#d6e3f5",
            "button_alt": "#eef4fd",
            "shadow_dark": "#7f9db9",
            "shadow_light": "#ffffff",
        },
        "Olive Retro": {
            "bg": "#d6d6c2",
            "panel": "#d9d3be",
            "panel_alt": "#ece7d5",
            "panel_soft": "#f5f1e5",
            "border": "#8a8673",
            "text": "#232117",
            "muted": "#5f5a46",
            "canvas": "#8d9278",
            "field": "#fffdf6",
            "field_border": "#9fa27f",
            "accent": "#4f6b2b",
            "accent_soft": "#cfd9b6",
            "button": "#d6d0b8",
            "button_alt": "#e8e2cb",
            "shadow_dark": "#8a8673",
            "shadow_light": "#fffdf6",
        },
        "Windows 98 Beige": {
            "bg": "#c9c1b2",
            "panel": "#d8d0c4",
            "panel_alt": "#efe7da",
            "panel_soft": "#f7f1e7",
            "border": "#8b8173",
            "text": "#1d1a16",
            "muted": "#655c52",
            "canvas": "#8f877c",
            "field": "#fffaf2",
            "field_border": "#9d9283",
            "accent": "#7a0000",
            "accent_soft": "#d8beb8",
            "button": "#d8d0c4",
            "button_alt": "#e8dfd1",
            "shadow_dark": "#8b8173",
            "shadow_light": "#fffaf2",
        },
        "Dark Retro": {
            "bg": "#2e2a26",
            "panel": "#3a342f",
            "panel_alt": "#4a433d",
            "panel_soft": "#544c45",
            "border": "#161311",
            "text": "#f2eadf",
            "muted": "#c2b5a3",
            "canvas": "#1b1714",
            "field": "#241f1b",
            "field_border": "#8a7a67",
            "accent": "#c86b2a",
            "accent_soft": "#7b6758",
            "button": "#4a433d",
            "button_alt": "#5a5148",
            "shadow_dark": "#161311",
            "shadow_light": "#7a6e62",
        },
        "Terminal Green": {
            "bg": "#0b120b",
            "panel": "#132013",
            "panel_alt": "#1a2a1a",
            "panel_soft": "#1f331f",
            "border": "#2f5a2f",
            "text": "#8cff8c",
            "muted": "#5fb35f",
            "canvas": "#050805",
            "field": "#091009",
            "field_border": "#2f5a2f",
            "accent": "#00ff66",
            "accent_soft": "#1f4f2c",
            "button": "#183018",
            "button_alt": "#204020",
            "shadow_dark": "#041004",
            "shadow_light": "#3b6f3b",
        },
    }
